---
title: "Datos koray"
author: "Nelly, Paul, Abel"
date: "5/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Cargar las librerias que usaremos para este trabajo
library(dplyr)
library(readr)
library(doBy)
library(reshape2)
library(ggplot2)

```



```{r}

#Cargar los archivos PAF

Z1_16S <- read_delim("data/Z1_16S_align_mock.paf", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

Z2_16S <- read_delim("data/Z2_16S_align_mock.paf", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

Z3_16S <- read_delim("data/Z3_16S_align_mock.paf", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

Z4_16S <- read_delim("data/Z4_16S_align_mock.paf", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

```


```{r}
#Seleccionamos unicamente 17 variables
dfz1<-Z1_16S[,1:17]
dfz2<-Z2_16S[,1:17]
dfz3<-Z3_16S[,1:17]
dfz4<-Z4_16S[,1:17]

#-----------------------------------------------------

#Asiganamos el nombre a nuestros datos
colnames(dfz1)<-c("Query","Q_length","Q_start","Q_end","Strand","op","T_length","T_start","T_end","N_res_matches","Align_block","MapQ","NM","ms","AS","nn","P_S")

colnames(dfz2)<-c("Query","Q_length","Q_start","Q_end","Strand","op","T_length","T_start","T_end","N_res_matches","Align_block","MapQ","NM","ms","AS","nn","P_S")

colnames(dfz3)<-c("Query","Q_length","Q_start","Q_end","Strand","op","T_length","T_start","T_end","N_res_matches","Align_block","MapQ","NM","ms","AS","nn","P_S")

colnames(dfz4)<-c("Query","Q_length","Q_start","Q_end","Strand","op","T_length","T_start","T_end","N_res_matches","Align_block","MapQ","NM","ms","AS","nn","P_S")
#-----------------------------------------------------
#Convertimos la variable AS como numerica
dfz1$AS <- as.numeric(gsub("AS:i:", "", dfz1$AS))
dfz2$AS <- as.numeric(gsub("AS:i:", "", dfz2$AS))
dfz3$AS <- as.numeric(gsub("AS:i:", "", dfz3$AS))
dfz4$AS <- as.numeric(gsub("AS:i:", "", dfz4$AS))
#-----------------------------------------------------

#LLamamos algunas columnas
df_z12<-cbind.data.frame(dfz1$Query,dfz1$op,dfz1$N_res_matches,dfz1$Align_block,dfz1$AS,dfz1$MapQ)

df_z22<-cbind.data.frame(dfz2$Query,dfz2$op,dfz2$N_res_matches,dfz2$Align_block,dfz2$AS,dfz2$MapQ)

df_z32<-cbind.data.frame(dfz3$Query,dfz3$op,dfz3$N_res_matches,dfz3$Align_block,dfz3$AS,dfz3$MapQ)

df_z42<-cbind.data.frame(dfz4$Query,dfz4$op,dfz4$N_res_matches,dfz4$Align_block,dfz4$AS,dfz4$MapQ)

#-----------------------------------------------------

colnames(df_z12)<-c("Query","op","N_res_matches","Align_block","AS","MapQ")

colnames(df_z22)<-c("Query","op","N_res_matches","Align_block","AS","MapQ")

colnames(df_z32)<-c("Query","op","N_res_matches","Align_block","AS","MapQ")
colnames(df_z42)<-c("Query","op","N_res_matches","Align_block","AS","MapQ")

#-----------------------------------------------------
# Con el Query hacemos que los duplicados se vayan

unique(df_z12$Query)
unique(df_z22$Query)
unique(df_z32$Query)
unique(df_z42$Query)
#-----------------------------------------------------

per.match<-(df_z12$N_res_matches/df_z12$Align_block)*100
df_2_modz1<-cbind.data.frame(df_z12,per.match)

per.match<-(df_z22$N_res_matches/df_z22$Align_block)*100
df_2_modz2<-cbind.data.frame(df_z22,per.match)

per.match<-(df_z32$N_res_matches/df_z32$Align_block)*100
df_2_modz3<-cbind.data.frame(df_z32,per.match)

per.match<-(df_z42$N_res_matches/df_z42$Align_block)*100
df_2_modz4<-cbind.data.frame(df_z42,per.match)
#-----------------------------------------------------
# llamamos el archivos txt, el cul tiene el nombre de los operones asi como la identificacion de las especies.
tax<-read.csv("rrn_tax.txt",sep = "\t")

#buscarv_tax<-merge(df_2,tax, by="op") ##revision
buscarv_taxz1<-merge(df_2_modz1,tax, by="op")
buscarv_taxz2<-merge(df_2_modz2,tax, by="op")
buscarv_taxz3<-merge(df_2_modz3,tax, by="op")
buscarv_taxz4<-merge(df_2_modz4,tax, by="op")
#-----------------------------------------------------
#Buscamos la varibles dadas

colnames(buscarv_taxz1)<-c("op","Query","N_res_matches","Align_block","AS","MapQ", "Matching","Tax")

colnames(buscarv_taxz2)<-c("op","Query","N_res_matches","Align_block","AS","MapQ", "Matching","Tax")

colnames(buscarv_taxz3)<-c("op","Query","N_res_matches","Align_block","AS","MapQ", "Matching","Tax")

colnames(buscarv_taxz4)<-c("op","Query","N_res_matches","Align_block","AS","MapQ", "Matching","Tax")
#-----------------------------------------------------

##For the 16S rRNA gene
df_3z1<-subset(buscarv_taxz1, Align_block > 999)

df_3z2<-subset(buscarv_taxz2, Align_block > 999)

df_3z3<-subset(buscarv_taxz3, Align_block > 999)

df_3z4<-subset(buscarv_taxz4, Align_block > 999)
```

```{r}

df_4z1<- summaryBy(AS ~ Query + Tax + Matching + MapQ, data=df_3z1, FUN=max)

df_4z2<- summaryBy(AS ~ Query + Tax + Matching + MapQ, data=df_3z2, FUN=max)

df_4z3<- summaryBy(AS ~ Query + Tax + Matching + MapQ, data=df_3z3, FUN=max)

df_4z4<- summaryBy(AS ~ Query + Tax + Matching + MapQ, data=df_3z4, FUN=max)
#-----------------------------------------------------

df_5z1<-df_4z1[!(duplicated(df_4z1$Query) | duplicated(df_4z1$Query, fromLast = TRUE)), ]  # unique tax records

df_5z2<-df_4z2[!(duplicated(df_4z1$Query) | duplicated(df_4z2$Query, fromLast = TRUE)), ]  # unique tax records

df_5z3<-df_4z3[!(duplicated(df_4z3$Query) | duplicated(df_4z3$Query, fromLast = TRUE)), ]  # unique tax records

df_5z4<-df_4z4[!(duplicated(df_4z4$Query) | duplicated(df_4z4$Query, fromLast = TRUE)), ]  # unique tax records
#-----------------------------------------------------
df_dupz1<-df_4z1[(duplicated(df_4z1$Query) | duplicated(df_4z1$Query, fromLast = TRUE)), ] # replicates

df_dupz2<-df_4z2[(duplicated(df_4z2$Query) | duplicated(df_4z2$Query, fromLast = TRUE)), ] # replicates

df_dupz3<-df_4z3[(duplicated(df_4z3$Query) | duplicated(df_4z3$Query, fromLast = TRUE)), ] # replicates

df_dupz4<-df_4z4[(duplicated(df_4z4$Query) | duplicated(df_4z4$Query, fromLast = TRUE)), ] # replicates
#-----------------------------------------------------
df_dup2z1<- df_dupz1[order(df_dupz1$Query, -abs(df_dupz1$AS) ), ] # sort by Query & AS value (highest to lowest)

df_dup2z2<- df_dupz2[order(df_dupz2$Query, -abs(df_dupz2$AS) ), ] # sort by Query & AS value (highest to lowest)

df_dup2z3<- df_dupz3[order(df_dupz3$Query, -abs(df_dupz3$AS) ), ] # sort by Query & AS value (highest to lowest)

df_dup2z4<- df_dupz4[order(df_dupz4$Query, -abs(df_dupz4$AS) ), ] # sort by Query & AS value (highest to lowest)

#-----------------------------------------------------
df_6z1<-df_dup2z1[ !duplicated(df_dup2z1$Query), ]    
df_6z2<-df_dup2z2[ !duplicated(df_dup2z2$Query), ] 
df_6z3<-df_dup2z3[ !duplicated(df_dup2z3$Query), ] 
df_6z4<-df_dup2z4[ !duplicated(df_dup2z4$Query), ] 

# take the first row within each Query
#-----------------------------------------------------

df_7z1 <-rbind.data.frame(df_5z1,df_6z1) 
write.csv(df_7z1, file = "Z1_16S_Qscores.csv")     # Quality scores file

df_7z2 <-rbind.data.frame(df_5z2,df_6z2) 
write.csv(df_7z2, file = "Z2_16S_Qscores.csv")     # Quality scores file

df_7z3 <-rbind.data.frame(df_5z3,df_6z3) 
write.csv(df_7z3, file = "Z3_16S_Qscores.csv")     # Quality scores file

df_7z4 <-rbind.data.frame(df_5z4,df_6z4) 
write.csv(df_7z4, file = "Z4_16S_Qscores.csv")     # Quality scores file

```


```{r}
Tax_tablez1<-dcast(data=melt(df_7z1$Tax, id.vars="Tax"), value ~ .)
colnames(Tax_tablez1) <- c("Tax","Counts")
rel.abz1 <- Tax_tablez1$Counts/sum(Tax_tablez1$Counts)
readsz1<-sum(Tax_tablez1$Counts)
readsz1

Tax_tablez2<-dcast(data=melt(df_7z2$Tax, id.vars="Tax"), value ~ .)
colnames(Tax_tablez2) <- c("Tax","Counts")
rel.abz2 <- Tax_tablez2$Counts/sum(Tax_tablez2$Counts)
readsz2<-sum(Tax_tablez2$Counts)
readsz2

Tax_tablez3<-dcast(data=melt(df_7z3$Tax, id.vars="Tax"), value ~ .)
colnames(Tax_tablez3) <- c("Tax","Counts")
rel.abz3 <- Tax_tablez3$Counts/sum(Tax_tablez3$Counts)
readsz3<-sum(Tax_tablez3$Counts)
readsz3

Tax_tablez4<-dcast(data=melt(df_7z4$Tax, id.vars="Tax"), value ~ .)
colnames(Tax_tablez4) <- c("Tax","Counts")
rel.abz4 <- Tax_tablez4$Counts/sum(Tax_tablez4$Counts)
readsz4<-sum(Tax_tablez4$Counts)
readsz4
#-----------------------------------------------------

Tax_table_RAz1<-cbind(Tax_tablez1, rel.abz1,"Z1_16S")
colnames(Tax_table_RAz1) <- c("Tax","Counts","RA","SampleID")
write.csv(Tax_table_RAz1, file = "Z1_16S_Tax_summ.csv")      # Taxa summary file

Tax_table_RAz2<-cbind(Tax_tablez2, rel.abz2,"Z2_16S")
colnames(Tax_table_RAz2) <- c("Tax","Counts","RA","SampleID")
write.csv(Tax_table_RAz2, file = "Z2_16S_Tax_summ.csv")      # Taxa summary file

Tax_table_RAz3<-cbind(Tax_tablez3, rel.abz3,"Z3_16S")
colnames(Tax_table_RAz3) <- c("Tax","Counts","RA","SampleID")
write.csv(Tax_table_RAz3, file = "Z3_16S_Tax_summ.csv")      # Taxa summary file

Tax_table_RAz4<-cbind(Tax_tablez4, rel.abz4,"Z4_16S")
colnames(Tax_table_RAz4) <- c("Tax","Counts","RA","SampleID")
write.csv(Tax_table_RAz4, file = "Z4_16S_Tax_summ.csv")      # Taxa summary file

```



#Apartir de aqui comienzan los analisis para realizar los gráficos.

```{r}
plot_z1 <- read_delim("all_summ.csv", ",", escape_double = FALSE, col_names = TRUE, trim_ws = TRUE)

plot1 <- ggplot(plot_z1, aes(x = SampleID, y = Counts, fill = Tax,)) + geom_bar(aes(), stat="identity", position="stack") 
#-----------------------------------------------------

#plot_z2 <- read_delim("Z2_16S_Tax_summ.csv", ",", escape_double = FALSE, col_names = TRUE, trim_ws = TRUE)

#plot2 <- ggplot(plot_z2, aes(x = SampleID, y = Counts, fill = Tax,)) + geom_bar(aes(), stat="identity", position="stack")
#-----------------------------------------------------

#plot_z3 <- read_delim("Z3_16S_Tax_summ.csv", ",", escape_double = FALSE, col_names = TRUE, trim_ws = TRUE)

#plot3 <- ggplot(plot_z3, aes(x = SampleID, y = Counts, fill = Tax,)) + geom_bar(aes(), stat="identity", position="stack")
#-----------------------------------------------------

#plot_z2 <- read_delim("Z2_16S_Tax_summ.csv", ",", escape_double = FALSE, col_names = TRUE, trim_ws = TRUE)

#plot2 <- ggplot(plot_z2, aes(x = SampleID, y = Counts, fill = Tax,)) + geom_bar(aes(), stat="identity", position="stack")
#-----------------------------------------------------

#plot1+ scale_fill_distiller(palette = 'Spectral')
#plot1+ scale_fill_gradient()


plot1 + scale_color_viridis(discrete = TRUE)
#plot1 + scale_color_gradientn(colours = rainbow(5))
#save plot to working directory
#ggsave(plot1,filename="Koraydata.png",height=9,width=12,units="in",dpi=200)

```


```{r}

#Gráfica mapa de calor

plot2 <- read_delim("all_summ.csv", ",", escape_double = FALSE, col_names = TRUE, trim_ws = TRUE)

library(ggplot2)
plot3 <- ggplot(plot2, aes(x = SampleID, y = Tax, fill = Counts,)) + geom_tile() + scale_fill_distiller(palette = 'YlGnBu')

#plot3+ scale_fill_distiller(palette = 'blues')
#plot3+ scale_fill_gradient()
plot3
#save plot to working directory
#ggsave(plot3,filename="Koraydata2.png",height=9,width=12,units="in",dpi=200)
```

```{r}
#genera una grafica con todas las muestras

plot_10z <- read_delim("all_summ.csv", ",", escape_double = FALSE, col_names = TRUE, trim_ws = TRUE)

#ab.tab$Sequence <- reorder(ab.tab$Sequence, ab.tab$Abundance)
plot_10z$Tax <- reorder(plot_10z$Tax, plot_10z$Counts)
#ab.tab$Sequence <- factor(ab.tab$Sequence,levels=rev(levels(ab.tab$Sequence)))
plot_10z$Tax <- factor(plot_10z$Tax,levels=rev(levels(plot_10z$Tax)))

plot_best21 <- ggplot(plot_10z, aes(x = SampleID, y = Counts, fill = Tax,)) + geom_bar(aes(), stat="identity", position="stack")

plot_best21 + theme(legend.title = element_text(size=15, 
                                      face="bold")) +theme(axis.text=element_text(size=15),
        axis.title=element_text(size=15,face="bold")) + theme(axis.text.x=element_text(angle=90,hjust=1))

#save plot to working directory
#ggsave(plot_best21,filename="Koraydata2-sorted.png",height=9,width=12,units="in",dpi=200)

```


```{r}

#Graficamos los 10 mejores reads que fueron asignados

df_10 <- plot_10z %>% 
arrange(desc(Counts)) %>% 
group_by(SampleID) %>% slice(1:10)

#ab.tab$Sequence <- reorder(ab.tab$Sequence, ab.tab$Abundance)
df_10$Tax <- reorder(df_10$Tax, df_10$Counts)
#ab.tab$Sequence <- factor(ab.tab$Sequence,levels=rev(levels(ab.tab$Sequence)))
df_10$Tax <- factor(df_10$Tax,levels=rev(levels(df_10$Tax)))

plot_best1 <- ggplot(df_10, aes(x = SampleID, y = Counts, fill = Tax,)) + geom_bar(aes(), stat="identity", position="stack")

plot_best1 + theme(legend.title = element_text(size=15, 
                                      face="bold")) +theme(axis.text=element_text(size=15),
        axis.title=element_text(size=15,face="bold")) + theme(axis.text.x=element_text(angle=90,hjust=1))

#save plot to working directory
#ggsave(plot_best1,filename="Koraydata-10best-sorted.png",height=9,width=12,units="in",dpi=200)

```
